### PR TITLE
Travis integration

### PR DESCRIPTION
**Pull request by Andy9822**
TravisCI integration implemented #1 

Simply link your repo to your Travis account and it's ready to go.

### CODE REVIEW

**Comment by Andy9822** [comment]
> Why you have package-lock and truffle-config ?

`truffle-config` was generated when I setup `truffle` for test automation and then be able to integrate with travis. So I just commited it as a config file

`package-lock.json` was already in your project and after all the setup it was updated so I decided to commit it too once it contains all the dependencies (and its versions) that your project needs

Do you have anything to say different or that could be done different? 
Let me know if it's the case, no problems.

**Comment by kushthedude** [comment]
> `package-lock.json` was already in your project and after all the setup it was updated so I decided to commit it too once it contains all the dependencies (and its versions) that your project needs

Remove the json, As we don't know how it can break the app.

**Comment by Andy9822** [comment]
Done @kushthedude 
I've just removed the json as you asked

**Comment by kushthedude** [comment]
> Done @kushthedude
> I've just removed the json as you asked

No you done it wrong, Actually you had to remove the changes you made in the `lock.json` rather you removed the complete file. Please change it else its ready for approval. 
Thanks

**Comment by Andy9822** [comment]
> > Done @kushthedude
> > I've just removed the json as you asked
> 
> @Andy9822
> No, you did it wrong, Actually, you had to remove the changes you made in the `lock.json` rather you removed the complete file. Please change it else it's ready for approval.
> Thanks

Oh yes, I'm sorry. I wasn't paying attention when I did the comit, you're right.
I've just reverted it and commited.

**Comment by Andy9822** [comment]
And also let me know if antything happens.
I tested linking my fork with my Travis account and it worked perfectly.

Thx

**Comment by kushthedude** [comment]
Perfect!

**Pull request merged**
